x-airflow-common: &airflow-common
  volumes:
    - ./include:/usr/local/airflow/include

services:

  # =====================================================
  # SPARK MASTER
  # =====================================================
  spark-master:
    image: apache/spark:4.1.2

    container_name: spark-master
    hostname: spark-master

    command: >
      bash -c "
      mkdir -p /tmp/spark /tmp/models &&
      /opt/spark/bin/spark-class
      org.apache.spark.deploy.master.Master
      "

    ports:
      - "8081:8080"
      - "7077:7077"

    environment:
      - MODEL_PATH=/tmp/models
      - SPARK_LOCAL_DIRS=/tmp/spark

    volumes:
      - ./include:/usr/local/airflow/include
      - ./apps:/opt/spark-apps

      # ✅ WINDOWS SAFE MODEL MOUNT
      - C:/spark-models:/tmp/models

      # optional local spark data
      - C:/spark-data:/tmp/spark-data

    networks:
      - airflow


  # =====================================================
  # SPARK WORKER
  # =====================================================
  spark-worker:
    image: apache/spark:4.1.2

    container_name: spark-worker
    hostname: spark-worker

    command: >
      bash -c "
      mkdir -p /tmp/spark /tmp/models &&
      /opt/spark/bin/spark-class
      org.apache.spark.deploy.worker.Worker
      spark://spark-master:7077
      "

    environment:
      - SPARK_WORKER_CORES=7
      - SPARK_WORKER_MEMORY=10G
      - MODEL_PATH=/tmp/models
      - SPARK_LOCAL_DIRS=/tmp/spark

    depends_on:
      - spark-master

    volumes:
      - ./include:/usr/local/airflow/include
      - ./apps:/opt/spark-apps

      # ✅ SAME WINDOWS MOUNT (MUST MATCH MASTER)
      - C:/spark-models:/tmp/models

      - C:/spark-data:/tmp/spark-data

    networks:
      - airflow


# =====================================================
# NETWORK
# =====================================================
networks:
  airflow:
    driver: bridge