x-airflow-common: &airflow-common
  volumes:
    - ./include:/usr/local/airflow/include

services:

  spark-master:
    image: apache/spark:4.1.2

    command: >
      bash -c "
      mkdir -p /tmp/spark /tmp/models &&
      /opt/spark/bin/spark-class
      org.apache.spark.deploy.master.Master
      "

    environment:
      - MODEL_PATH=/tmp/models
      - SPARK_LOCAL_DIRS=/tmp/spark

    volumes:
      - ./include:/usr/local/airflow/include
      - ./apps:/opt/spark-apps
      - ./data:/tmp/spark-data
      - ./models:/tmp/models

    ports:
      - "8081:8080"
      - "7077:7077"

    networks:
      - airflow


  spark-worker:
    image: apache/spark:4.1.2

    command: >
      bash -c "
      mkdir -p /tmp/spark /tmp/models &&
      /opt/spark/bin/spark-class
      org.apache.spark.deploy.worker.Worker
      spark://spark-master:7077
      "

    environment:
      - SPARK_WORKER_CORES=7
      - SPARK_WORKER_MEMORY=10G
      - MODEL_PATH=/tmp/models
      - SPARK_LOCAL_DIRS=/tmp/spark

    depends_on:
      - spark-master

    volumes:
      - ./include:/usr/local/airflow/include
      - ./apps:/opt/spark-apps
      - ./data:/tmp/spark-data
      - ./models:/tmp/models

    networks:
      - airflow


networks:
  airflow:
    driver: bridge