version: '3.8'

services:

  scheduler:
    volumes:
      - C:/spark-models:/tmp/models

  webserver:
    volumes:
      - C:/spark-models:/tmp/models

  triggerer:
    volumes:
      - C:/spark-models:/tmp/models

  spark-master:
    image: apache/spark:4.1.2
    container_name: spark-master
    hostname: spark-master
    user: root

    command: >
      bash -c "
      mkdir -p /tmp/spark &&
      mkdir -p /tmp/models &&
      chmod -R 777 /tmp/models &&
      chmod -R 777 /tmp/spark &&
      /opt/spark/bin/spark-class
      org.apache.spark.deploy.master.Master
      "

    ports:
      - "8081:8080"
      - "7077:7077"

    environment:
      - MODEL_PATH=/tmp/models
      - SPARK_LOCAL_DIRS=/tmp/spark

    volumes:
      - ./include:/usr/local/airflow/include
      - ./apps:/opt/spark-apps
      - C:/spark-models:/tmp/models
      - C:/spark-data:/tmp/spark-data

    networks:
      - airflow

  spark-worker:
    image: apache/spark:4.1.2
    container_name: spark-worker
    hostname: spark-worker
    user: root

    command: >
      bash -c "
      mkdir -p /tmp/spark &&
      mkdir -p /tmp/models &&
      chmod -R 777 /tmp/models &&
      chmod -R 777 /tmp/spark &&
      /opt/spark/bin/spark-class
      org.apache.spark.deploy.worker.Worker
      spark://spark-master:7077
      "

    environment:
      - SPARK_WORKER_CORES=7
      - SPARK_WORKER_MEMORY=10G
      - MODEL_PATH=/tmp/models
      - SPARK_LOCAL_DIRS=/tmp/spark

    depends_on:
      - spark-master

    volumes:
      - ./include:/usr/local/airflow/include
      - ./apps:/opt/spark-apps
      - C:/spark-models:/tmp/models
      - C:/spark-data:/tmp/spark-data

    networks:
      - airflow

networks:
  airflow:
    driver: bridge