import json
import logging
import joblib
import pandas as pd
import psycopg2

from mf_advisor.service.abstract_base_service import (
    AbstractBaseService
)

logging.basicConfig(level=logging.INFO)

POSTGRES_DRIVER = "org.postgresql.Driver"
MODEL_PATH = "C:/spark-models/random_forest.pkl"

FEATURE_COLUMNS = [
    "daily_return_pct",
    "weekly_return_pct",
    "monthly_return_pct",
    "rolling_return_30d_pct",
    "rolling_return_90d_pct",
    "moving_avg_7d",
    "moving_avg_30d",
    "moving_avg_90d",
    "moving_avg_200d",
    "cagr_percent",
    "sharpe_ratio",
    "annualized_volatility"
]


class PortfolioRebalanceService(AbstractBaseService):

    def __init__(self):
        super().__init__()

        self.rebalance_prompt = """
You are a professional Mutual Fund Portfolio Advisor.

You will receive:

1. User risk profile
2. Detailed mutual fund analytics generated by a machine learning model

Your task:

- Analyze the portfolio.
- Explain strengths and weaknesses.
- Explain why funds should be INCREASE, HOLD, or REDUCE.
- Use all provided fund metrics while generating recommendations.

Consider:

- predicted_return
- sharpe_ratio
- annualized_volatility
- portfolio_score
- cagr_percent
- rolling returns
- momentum indicators
- historical performance indicators

Provide:

1. Portfolio Summary
2. Strengths
3. Risks
4. Fund Recommendations
5. Rebalance Strategy

IMPORTANT:

- Return ONLY valid JSON.
- Keep recommendations concise.
- Do NOT return raw metrics.
- Do NOT return scheme codes.

Example:

{
  "portfolio_summary":"Portfolio has moderate growth potential but weak risk-adjusted returns.",
  "strengths":[
    "Positive recent return trends."
  ],
  "risks":[
    "Negative risk-adjusted performance."
  ],
  "fund_recommendations":[
    {
      "action":"REDUCE",
      "reason":"Weak risk-return profile."
    }
  ],
  "rebalance_strategy":"Reduce low-scoring funds and move capital toward stronger risk-adjusted opportunities."
}
"""

    def rebalance_portfolio(self, portfolio_req):

        try:

            logging.info(
                f"Portfolio request: {portfolio_req}"
            )

            fund_names = self.extract_fund_names(
                portfolio_req
            )

            scheme_codes = self.fetch_scheme_codes(
                fund_names
            )

            if not scheme_codes:

                return {
                    "risk_profile":
                        portfolio_req.get(
                            "risk_profile"
                        ),
                    "ml_recommendations": [],
                    "portfolio_summary": "",
                    "strengths": [],
                    "risks": [],
                    "fund_recommendations": [],
                    "rebalance_strategy": ""
                }

            latest_metrics_df = (
                self.load_latest_fund_metrics(
                    scheme_codes
                )
            )

            ranked_funds = (
                self.predict_rank_and_recommend(
                    latest_metrics_df
                )
            )

            llm_analysis = (
                self.generate_llm_recommendation(
                    portfolio_req.get(
                        "risk_profile"
                    ),
                    ranked_funds
                )
            )

            ui_recommendations = (
                self.build_ui_recommendations(
                    ranked_funds
                )
            )

            return {
                "risk_profile":
                    portfolio_req.get(
                        "risk_profile"
                    ),

                "ml_recommendations":
                    ui_recommendations,

                "portfolio_summary":
                    llm_analysis.get(
                        "portfolio_summary",
                        ""
                    ),

                "strengths":
                    llm_analysis.get(
                        "strengths",
                        []
                    ),

                "risks":
                    llm_analysis.get(
                        "risks",
                        []
                    ),

                "fund_recommendations":
                    llm_analysis.get(
                        "fund_recommendations",
                        []
                    ),

                "rebalance_strategy":
                    llm_analysis.get(
                        "rebalance_strategy",
                        ""
                    )
            }

        except Exception:

            logging.exception(
                "Error while processing portfolio request"
            )

            raise

    def extract_fund_names(
            self,
            portfolio_req
    ):

        return [
            fund.get("name")
            for fund in portfolio_req.get(
                "funds",
                []
            )
            if fund.get("name")
        ]

    def fetch_scheme_codes(
            self,
            fund_names
    ):

        if not fund_names:
            return []

        placeholders = ",".join(
            ["%s"] * len(fund_names)
        )

        query = f"""
        SELECT
            scheme_code
        FROM mf_schemes
        WHERE scheme_name IN ({placeholders})
        """

        conn = psycopg2.connect(
            host=self.connection["host"],
            port=self.connection["port"],
            database=self.connection["database"],
            user=self.connection["user"],
            password=self.connection["password"]
        )

        try:

            with conn.cursor() as cursor:

                cursor.execute(
                    query,
                    tuple(fund_names)
                )

                rows = cursor.fetchall()

                return [
                    int(row[0])
                    for row in rows
                ]

        finally:
            conn.close()

    def load_latest_fund_metrics(
            self,
            scheme_codes
    ):

        scheme_list = ",".join(
            map(str, scheme_codes)
        )

        query = f"""
        (
            SELECT *
            FROM
            (
                SELECT
                    scheme_code,
                    nav_date,
                    daily_return_pct,
                    weekly_return_pct,
                    monthly_return_pct,
                    rolling_return_30d_pct,
                    rolling_return_90d_pct,
                    moving_avg_7d,
                    moving_avg_30d,
                    moving_avg_90d,
                    moving_avg_200d,
                    cagr_percent,
                    sharpe_ratio,
                    annualized_volatility,
                    ROW_NUMBER() OVER
                    (
                        PARTITION BY scheme_code
                        ORDER BY nav_date DESC
                    ) rn
                FROM mf_final_nav_enriched
                WHERE scheme_code IN ({scheme_list})
            ) t
            WHERE rn = 1
        ) latest_data
        """

        jdbc_url = (
            f"jdbc:postgresql://"
            f"{self.connection['host']}:"
            f"{self.connection['port']}/"
            f"{self.connection['database']}"
        )

        return (
            self.spark.read
            .format("jdbc")
            .option("url", jdbc_url)
            .option("dbtable", query)
            .option("user", self.connection["user"])
            .option("password", self.connection["password"])
            .option("driver", POSTGRES_DRIVER)
            .load()
        )

    def load_model(self):

        logging.info(
            f"Loading model from {MODEL_PATH}"
        )

        return joblib.load(
            MODEL_PATH
        )

    def predict_rank_and_recommend(
            self,
            latest_metrics_df
    ):

        model = self.load_model()

        pandas_df = (
            latest_metrics_df.toPandas()
        )

        if pandas_df.empty:
            return []

        for column_name in FEATURE_COLUMNS:

            pandas_df[column_name] = (
                pd.to_numeric(
                    pandas_df[column_name],
                    errors="coerce"
                )
                .fillna(0)
                .astype(float)
            )

        X = pandas_df[
            FEATURE_COLUMNS
        ]

        pandas_df["predicted_return"] = (
            model.predict(X)
        )

        pandas_df["portfolio_score"] = (
                pandas_df["predicted_return"] * 0.50
                + pandas_df["sharpe_ratio"] * 0.30
                - pandas_df["annualized_volatility"] * 0.20
        )

        pandas_df["recommendation"] = (
            pandas_df["portfolio_score"]
            .apply(
                lambda x:
                "INCREASE"
                if x >= 5
                else (
                    "HOLD"
                    if x >= 2
                    else "REDUCE"
                )
            )
        )

        pandas_df = (
            pandas_df.sort_values(
                by="portfolio_score",
                ascending=False
            )
        )

        return pandas_df.to_dict(
            orient="records"
        )

    def build_ui_recommendations(
            self,
            ranked_funds
    ):

        recommendations = []

        for fund in ranked_funds:

            recommendations.append(
                {
                    "predicted_return":
                        round(
                            float(
                                fund.get(
                                    "predicted_return",
                                    0
                                )
                            ),
                            4
                        ),

                    "sharpe_ratio":
                        round(
                            float(
                                fund.get(
                                    "sharpe_ratio",
                                    0
                                )
                            ),
                            4
                        ),

                    "annualized_volatility":
                        round(
                            float(
                                fund.get(
                                    "annualized_volatility",
                                    0
                                )
                            ),
                            4
                        ),

                    "portfolio_score":
                        round(
                            float(
                                fund.get(
                                    "portfolio_score",
                                    0
                                )
                            ),
                            4
                        ),

                    "recommendation":
                        fund.get(
                            "recommendation",
                            "HOLD"
                        )
                }
            )

        return recommendations

    def generate_llm_recommendation(
            self,
            risk_profile,
            ranked_funds
    ):

        payload = {
            "risk_profile":
                risk_profile,

            # Full dataset passed to LLM
            "funds":
                ranked_funds
        }

        response = self.invoke_llm(
            system_prompt=
            self.rebalance_prompt,

            user_prompt=
            json.dumps(
                payload,
                default=str,
                indent=2
            ),

            temperature=0.2,

            json_response=True
        )

        logging.info(
            f"LLM Recommendation: {response}"
        )

        return json.loads(
            response
        )